# Generated by Django 4.2 on 2024-06-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0079_merge_20240602_1739'),
        ('journal', '0065_prepub_send_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
                ('sections', models.ManyToManyField(blank=True, to='submission.section')),
            ],
        ),
    ]
